# Generated by Django 3.2.5 on 2021-07-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_driverprofilecomment_comment_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverprofilecomment',
            old_name='driver_profile_id',
            new_name='profile_id',
        ),
    ]
