# Generated by Django 3.2.5 on 2021-08-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmember',
            options={'verbose_name': 'Chat member', 'verbose_name_plural': 'Chat members'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Chat message', 'verbose_name_plural': 'Chat messages'},
        ),
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': 'Chat room', 'verbose_name_plural': 'Chat rooms'},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default='2021-10-09 20:00:00'),
            preserve_default=False,
        ),
    ]
