# Generated by Django 3.2.5 on 2021-07-29 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='License title')),
            ],
            options={
                'verbose_name': 'Driving license',
                'verbose_name_plural': 'Driving licenses',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_time', models.DateTimeField(verbose_name='Race start date and time')),
                ('supply_time', models.DateTimeField(verbose_name='Race end date and time')),
                ('pickup_location', models.CharField(max_length=300, verbose_name='Race products pickup location')),
                ('supply_location', models.CharField(max_length=300, verbose_name='Race products supply location')),
                ('status', models.CharField(choices=[('S', 'STARTED'), ('P', 'PENDING'), ('E', 'ENDED'), ('C', 'CANCELED')], default='P', max_length=1, verbose_name='Race status')),
            ],
            options={
                'verbose_name': 'Race',
                'verbose_name_plural': 'Races',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Vehicle model title')),
                ('mark', models.CharField(max_length=100, verbose_name='Vehicle mark title')),
                ('drivers_limit', models.PositiveSmallIntegerField(default=1, verbose_name='Vehicle drivers limit')),
                ('driving_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_delivery.drivinglicense', verbose_name='Required driving category')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
    ]
