# Generated by Django 3.2.5 on 2021-07-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='drivers_limit',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Vehicle drivers limit'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mark',
            field=models.CharField(max_length=100, verbose_name='Vehicle mark title'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Vehicle model title'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='using',
            field=models.BooleanField(default=False, editable=False, verbose_name='Vehicle in use flag'),
        ),
    ]
