# Generated by Django 3.2.5 on 2021-07-29 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('car_delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='driver_vehicle_driver', to='profiles.driverprofile', verbose_name='Driver'),
        ),
        migrations.AddField(
            model_name='race',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='vehicle_vehicle_driver', to='car_delivery.vehicle', verbose_name='Vehicle'),
        ),
    ]
