# Generated by Django 3.2.5 on 2021-08-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_delivery', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivinglicense',
            name='title',
            field=models.CharField(max_length=10, unique=True, verbose_name='License title'),
        ),
    ]
