# Generated by Django 3.2.5 on 2021-07-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_delivery', '0005_driver_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={'verbose_name': 'Race', 'verbose_name_plural': 'Races'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='using',
        ),
        migrations.AlterField(
            model_name='race',
            name='status',
            field=models.CharField(choices=[('S', 'STARTED'), ('P', 'PENDING'), ('E', 'ENDED'), ('C', 'CANCELED')], default='P', max_length=1, verbose_name='Race status'),
        ),
    ]
