# Generated by Django 3.2.5 on 2021-07-29 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_driverprofile'),
        ('car_delivery', '0007_remove_driver_driving_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='driver_vehicle_driver', to='profiles.driverprofile', verbose_name='Driver'),
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
