# Generated by Django 3.2.5 on 2021-07-27 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Driver firstname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Driver lastname')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='DrivingLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='License title')),
            ],
            options={
                'verbose_name': 'Driving license',
                'verbose_name_plural': 'Driving licenses',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Car model title')),
                ('mark', models.CharField(max_length=100, verbose_name='Car mark title')),
                ('using', models.BooleanField(default=False, editable=False, verbose_name='Car in use flag')),
                ('drivers_limit', models.PositiveSmallIntegerField(default=1, verbose_name='Car drivers limit')),
                ('driving_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDelivery.drivinglicense', verbose_name='Required driving category')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='driver_vehicle_driver', to='CarDelivery.driver', verbose_name='Driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='vehicle_vehicle_driver', to='CarDelivery.vehicle', verbose_name='Vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='driving_license',
            field=models.ManyToManyField(to='CarDelivery.DrivingLicense', verbose_name='Driving license'),
        ),
    ]
